### ISSUE TITLE
Future OF COSI

### ISSUE THREAD

**Issue by sajanjswl** [kubernetes-sigs/container-object-storage-interface-spec#17]
# Enhancement
The objective of this Issue is to track and discuss the changes that are yet to be made or has already been made to the Protocol Field in Bucket Class. This is also to discuss and come up with ideas on how we should brand COSI. Few discussions have started within the COSI community to change the name "COSI" and the two candidates we came up with are OSI, **K**OSI.

I think both the names are really good and we should try to have both. It might sound strange at first but I will try to clarify my self. 

OSI, can we have this name! My personal opinion will be that we are not quite mature enough for this name. As it will be "The Object Storage Interface" but we should definitely plan for it to be the future of COSI.

KOSI, I think this name suits the current position of COSI. We should plan for creating a standard for object storage in Kubernetes. Since anyway we are already doing it. Once we reach this goal then, we can plan for OSI.

For this to happen we will have to re-discuss the Protocol field in  Bucket Class.
 
Parameters: Final Conclusion
```
BucketClass

provisioner: s3.amazonaws.com
protocol: 
  name: s3
  version: 2012-11-05
anonymousAccessMode: Public
releasePolicy: Retain
allowedNamespaces:
  - profiles
parameters: 
    region: us-east-1
```
 ### COSI ---> KOSI ----> OSI
