### ISSUE TITLE
[19-December-2023] - COSI Bucket Names

### ISSUE THREAD

**Issue by thotz** [kubernetes-sigs/container-object-storage-interface-spec#45]
Copy pasting request from https://github.com/rook/rook/issues/13396

When creating buckets with a bucket claim like this:
```yaml 
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClaim
metadata:
  name: my-bucket
spec:
  bucketClassName: ceph-bucket-class
  protocols:
    - s3
```
The bucket created is ceph is not my-bucket but instead a random auto generated name. In our use case we need to be able to create buckets with specified names. Is that possible somehow?
